options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'llm4soc-merge-handler-function',
          '--runtime', 'python311',
          '--trigger-event', 'google.storage.object.finalize',
          '--trigger-resource', 'main-asset-storage',
          '--entry-point', 'merge_handler',
          '--region', 'europe-west1',
          '--source', '.']
